/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4;

import java.util.HashSet;

/**
 *
 * @author Rafael
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form Frame1
     */
    public static HashSet<Alumno> listadoAlumnos = new HashSet<>();
    public static HashSet<Materia> listadoMaterias = new HashSet<>();

    public VistaPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        dtpEscritorio = new javax.swing.JDesktopPane();
        NavigatorMenu = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jMenuItemAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jMenuItemMateria = new javax.swing.JMenuItem();
        jmRegistro = new javax.swing.JMenu();
        jMenuItemRegistro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colegio");
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);

        dtpEscritorio.setPreferredSize(new java.awt.Dimension(600, 477));

        javax.swing.GroupLayout dtpEscritorioLayout = new javax.swing.GroupLayout(dtpEscritorio);
        dtpEscritorio.setLayout(dtpEscritorioLayout);
        dtpEscritorioLayout.setHorizontalGroup(
            dtpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dtpEscritorioLayout.setVerticalGroup(
            dtpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        NavigatorMenu.setMinimumSize(new java.awt.Dimension(600, 23));
        NavigatorMenu.setPreferredSize(new java.awt.Dimension(600, 23));

        jmAlumno.setText("Alumno");

        jMenuItemAlumno.setText("Registrar alumno");
        jMenuItemAlumno.addActionListener(this::jMenuItemAlumnoActionPerformed);
        jmAlumno.add(jMenuItemAlumno);

        NavigatorMenu.add(jmAlumno);

        jmMateria.setText("Materia");

        jMenuItemMateria.setText("Registrar materia");
        jMenuItemMateria.addActionListener(this::jMenuItemMateriaActionPerformed);
        jmMateria.add(jMenuItemMateria);

        NavigatorMenu.add(jmMateria);

        jmRegistro.setText("Registro");

        jMenuItemRegistro.setText("Formulario de registro");
        jMenuItemRegistro.addActionListener(this::jMenuItemRegistroActionPerformed);
        jmRegistro.add(jMenuItemRegistro);

        NavigatorMenu.add(jmRegistro);

        jMenu2.setText("Mostrar");

        jMenuItem1.setText("Mostrar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        NavigatorMenu.add(jMenu2);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenuSalir.add(jMenuItemSalir);

        NavigatorMenu.add(jMenuSalir);

        setJMenuBar(NavigatorMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpEscritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlumnoActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        VistaAlumnos va  = new VistaAlumnos(listadoAlumnos);
        va.setVisible(true);
        dtpEscritorio.add(va);
        dtpEscritorio.moveToFront(va);
    }//GEN-LAST:event_jMenuItemAlumnoActionPerformed

    private void jMenuItemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMateriaActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        VistaMaterias vistaMaterias = new VistaMaterias(listadoMaterias);
        vistaMaterias.setVisible(true);
        dtpEscritorio.add(vistaMaterias);
        dtpEscritorio.moveToFront(vistaMaterias);
    }//GEN-LAST:event_jMenuItemMateriaActionPerformed

    private void jMenuItemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        VistaInscripciones vistaInscripcion = new VistaInscripciones(listadoAlumnos, listadoMaterias);
        vistaInscripcion.setVisible(true);
        dtpEscritorio.add(vistaInscripcion);
        dtpEscritorio.moveToFront(vistaInscripcion);
    }//GEN-LAST:event_jMenuItemRegistroActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro que desea salir?", "Confirmación de salida", javax.swing.JOptionPane.YES_NO_OPTION);

        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dtpEscritorio.removeAll();
        dtpEscritorio.repaint();
        VistaMostrar vm = new VistaMostrar();
        vm.setVisible(true);
        dtpEscritorio.add(vm);
        dtpEscritorio.moveToFront(vm);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        Materia web2 = new Materia(1,"Web 2",2007);
        Materia mate = new Materia(2,"Matematicas",2008);
        Materia lab1 = new Materia(3,"Laboratorio 1",2009);
        
        Alumno alum1 = new Alumno(1001,"Lopez","Martin");
        Alumno alum2 = new Alumno(1002,"Martinez","Brenda");
        /*
        alum1.agregarMateria(web2);
        alum1.agregarMateria(mate);
        alum1.agregarMateria(lab1);
        
        alum2.agregarMateria(web2);
        alum2.agregarMateria(mate);
        alum2.agregarMateria(lab1);
        */
        listadoAlumnos.add(alum1);
        listadoAlumnos.add(alum2);
        
        listadoMaterias.add(web2);
        listadoMaterias.add(mate);
        listadoMaterias.add(lab1);
        
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar NavigatorMenu;
    private javax.swing.JDesktopPane dtpEscritorio;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAlumno;
    private javax.swing.JMenuItem jMenuItemMateria;
    private javax.swing.JMenuItem jMenuItemRegistro;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmRegistro;
    // End of variables declaration//GEN-END:variables
}
